<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find uos_common_urdf)/common.xacro" />

  <xacro:include filename="$(find kurt_base)/urdf/rotunit.urdf.xacro" />

  <xacro:property name="top_x" value="0.36" />
  <xacro:property name="top_y" value="0.28" />
  <xacro:property name="top_z" value="0.08" />
  <xacro:property name="top_mass" value="2.0" />
  <xacro:property name="rotunit_box_y_offset" value="-0.01" />
  
  <link name="kurt360_top">
    <visual>
      <geometry>
        <box size="${top_x} ${top_y} ${top_z}" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <material name="silver" >
          <color rgba=".7 .7 .7 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${top_x} ${top_y} ${top_z}" />
      </geometry>
    </collision>
    <xacro:box_inertial x="${top_x}" y="${top_y}" z="${top_z}" mass="${top_mass}" />
  </link>

  <joint name="laser_top_joint" type="fixed">
    <child link="rotunit_box_link" />
    <parent link="kurt360_top" />
    <origin xyz="0 ${rotunit_box_y_offset} ${top_z/2 + rotunit_box_z/2}" rpy="0 0 0" />
  </joint>
</robot>
